# Generated by Django 5.2.11 on 2026-02-21 16:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
